# States

In [7]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/master/Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv", sep=",")

In [3]:
df.head()

    Impfdatum  BundeslandId_Impfort  Impfstoff  Impfserie  Anzahl
0  2020-12-27                     1  Comirnaty          1     808
1  2020-12-27                     2  Comirnaty          1     443
2  2020-12-27                     3  Comirnaty          1     373
3  2020-12-27                     4  Comirnaty          1     510
4  2020-12-27                     4    Moderna          1       3

### J&J

In [31]:
df[(df["Impfserie"]==1) & (df["Impfstoff"]=="Janssen")].groupby(["Impfstoff"])["Anzahl"].sum().reset_index()

  Impfstoff   Anzahl
0   Janssen  3607772

In [30]:
df[(df["Impfserie"]==2) & (df["Impfstoff"]=="Janssen")].groupby(["Impfstoff"])["Anzahl"].sum().reset_index()

  Impfstoff  Anzahl
0   Janssen    2508

In [32]:
df[(df["Impfserie"]==3) & (df["Impfstoff"]=="Janssen")].groupby(["Impfstoff"])["Anzahl"].sum().reset_index()

  Impfstoff  Anzahl
0   Janssen   18498

### BionTech

In [33]:
df[(df["Impfserie"]==1) & (df["Impfstoff"]=="Comirnaty")].groupby(["Impfstoff"])["Anzahl"].sum().reset_index()

   Impfstoff    Anzahl
0  Comirnaty  45655569

In [34]:
df[(df["Impfserie"]==2) & (df["Impfstoff"]=="Comirnaty")].groupby(["Impfstoff"])["Anzahl"].sum().reset_index()

   Impfstoff    Anzahl
0  Comirnaty  49838682

In [35]:
df[(df["Impfserie"]==3) & (df["Impfstoff"]=="Comirnaty")].groupby(["Impfstoff"])["Anzahl"].sum().reset_index()

   Impfstoff    Anzahl
0  Comirnaty  30906222

### Erstimpfung

In [39]:
first = df[df["Impfserie"]==1].groupby(["Impfstoff"])["Anzahl"].sum().reset_index()
first["Anzahl"].sum()

63708286

In [40]:
second = df[df["Impfserie"]==2].groupby(["Impfstoff"])["Anzahl"].sum().reset_index()
second["Anzahl"].sum()

59625447

In [42]:
df[(df["Impfserie"]==1) & (df["Impfstoff"]=="Janssen")].groupby(["Impfstoff"])["Anzahl"].sum().reset_index()

  Impfstoff   Anzahl
0   Janssen  3607772

# Ratio

In [8]:
df_ratio = pd.read_csv("RKI_COVID19_Impfquotenmonitoring.csv", sep=",")

In [9]:
df_ratio.columns

Index(['timestamp', 'ISODate', 'IdBundesland', 'Bundesland',
       'Impfungenkumulativ', 'DifferenzzumVortag', 'IndikationnachAlter',
       'BeruflicheIndikation', 'MedizinischeIndikation',
       'PflegeheimbewohnerIn', 'ZweiteImpfungkumulativ',
       'ZweiteImpfungDifferenzzumVortag', 'Auffrischimpfungen'],
      dtype='object')

In [10]:
df_ratio.head()

,timestamp,ISODate,IdBundesland,Bundesland,Impfungenkumulativ,DifferenzzumVortag,IndikationnachAlter,BeruflicheIndikation,MedizinischeIndikation,PflegeheimbewohnerIn,ZweiteImpfungkumulativ,ZweiteImpfungDifferenzzumVortag,Auffrischimpfungen
0,1609113600,2020-12-28,0,Gesamt,21566,1357,5833,7618,962,11646,0,0,0
1,1609113600,2020-12-28,1,Schleswig-Holstein,809,0,213,239,344,553,0,0,0
2,1609113600,2020-12-28,2,Hamburg,445,0,197,222,0,223,0,0,0
3,1609113600,2020-12-28,3,Niedersachsen,334,0,42,116,140,306,0,0,0
4,1609113600,2020-12-28,4,Bremen,420,0,205,87,0,0,0,0,0

In [5]:
df_ratio["GEO"] = "DE"

In [6]:
df_ratio.head()

,timestamp,ISODate,IdBundesland,Bundesland,Impfungenkumulativ,DifferenzzumVortag,IndikationnachAlter,BeruflicheIndikation,MedizinischeIndikation,PflegeheimbewohnerIn,ZweiteImpfungkumulativ,ZweiteImpfungDifferenzzumVortag,Auffrischimpfungen,GEO
0,1609113600,2020-12-28,0,Gesamt,21566,1357,5833,7618,962,11646,0,0,0,DE
1,1609113600,2020-12-28,1,Schleswig-Holstein,809,0,213,239,344,553,0,0,0,DE
2,1609113600,2020-12-28,2,Hamburg,445,0,197,222,0,223,0,0,0,DE
3,1609113600,2020-12-28,3,Niedersachsen,334,0,42,116,140,306,0,0,0,DE
4,1609113600,2020-12-28,4,Bremen,420,0,205,87,0,0,0,0,0,DE

In [ ]:
df_ratio.rename()

In [63]:
df_ratio[(df_ratio["ISODate"]=="2022-04-09")]

,timestamp,ISODate,IdBundesland,Bundesland,Impfungenkumulativ,DifferenzzumVortag,IndikationnachAlter,BeruflicheIndikation,MedizinischeIndikation,PflegeheimbewohnerIn,ZweiteImpfungkumulativ,ZweiteImpfungDifferenzzumVortag,Auffrischimpfungen
7888,1649462400,2022-04-09,0,Gesamt,63706942,3533,-1,-1,-1,-1,63225075,8358,49010374
7889,1649462400,2022-04-09,1,Schleswig-Holstein,2343604,122,-1,-1,-1,-1,2351907,276,2100371
7890,1649462400,2022-04-09,2,Hamburg,1540889,198,-1,-1,-1,-1,1539967,186,1118149
7891,1649462400,2022-04-09,3,Niedersachsen,6283675,388,-1,-1,-1,-1,6220672,928,5090331
7892,1649462400,2022-04-09,4,Bremen,614768,37,-1,-1,-1,-1,607087,106,442115
7893,1649462400,2022-04-09,5,Nordrhein-Westfalen,14428518,834,-1,-1,-1,-1,14160381,1626,11045078
7894,1649462400,2022-04-09,6,Hessen,4834291,240,-1,-1,-1,-1,4699088,551,3572842
7895,1649462400,2022-04-09,7,Rheinland-Pfalz,3181172,108,-1,-1,-1,-1,3083259,333,2420558
7896,1649462400,2022-04-09,8,Baden-Württemberg,8217948,348,-1,-1,-1,-1,8242730,781,6349666
7897,1649462400,2022-04-09,9,Bayern,9730829,445,-1,-1,-1,-1,9831280,1258,7400599
7898,1649462400,2022-04-09,10,Saarland,811769,21,-1,-1,-1,-1,809976,85,650893
7899,1649462400,2022-04-09,11,Berlin,2847464,183,-1,-1,-1,-1,2826239,441,2195284
7900,1649462400,2022-04-09,12,Brandenburg,1757870,101,-1,-1,-1,-1,1748535,297,1316143
7901,1649462400,2022-04-09,13,Mecklenburg-Vorpommern,1198194,64,-1,-1,-1,-1,1199687,169,918766
7902,1649462400,2022-04-09,14,Sachsen,2654118,179,-1,-1,-1,-1,2620107,560,1958617
7903,1649462400,2022-04-09,15,Sachsen-Anhalt,1570377,112,-1,-1,-1,-1,1597988,363,1188239
7904,1649462400,2022-04-09,16,Thüringen,1489403,151,-1,-1,-1,-1,1491148,390,1100269

In [66]:
test = df_ratio[(df_ratio["ISODate"]=="2022-04-09") & (df_ratio["Bundesland"]!="Gesamt")]
result = test.groupby([test["ISODate"]]).sum().reset_index()
result

,ISODate,timestamp,IdBundesland,Impfungenkumulativ,DifferenzzumVortag,IndikationnachAlter,BeruflicheIndikation,MedizinischeIndikation,PflegeheimbewohnerIn,ZweiteImpfungkumulativ,ZweiteImpfungDifferenzzumVortag,Auffrischimpfungen
0,2022-04-09,26391398400,136,63504889,3531,-16,-16,-16,-16,63030051,8350,48867920

In [67]:
test2 = df_ratio.copy()

In [68]:
test2.head()

,timestamp,ISODate,IdBundesland,Bundesland,Impfungenkumulativ,DifferenzzumVortag,IndikationnachAlter,BeruflicheIndikation,MedizinischeIndikation,PflegeheimbewohnerIn,ZweiteImpfungkumulativ,ZweiteImpfungDifferenzzumVortag,Auffrischimpfungen
0,1609113600,2020-12-28,0,Gesamt,21566,1357,5833,7618,962,11646,0,0,0
1,1609113600,2020-12-28,1,Schleswig-Holstein,809,0,213,239,344,553,0,0,0
2,1609113600,2020-12-28,2,Hamburg,445,0,197,222,0,223,0,0,0
3,1609113600,2020-12-28,3,Niedersachsen,334,0,42,116,140,306,0,0,0
4,1609113600,2020-12-28,4,Bremen,420,0,205,87,0,0,0,0,0

In [69]:
test2.columns

Index(['timestamp', 'ISODate', 'IdBundesland', 'Bundesland',
       'Impfungenkumulativ', 'DifferenzzumVortag', 'IndikationnachAlter',
       'BeruflicheIndikation', 'MedizinischeIndikation',
       'PflegeheimbewohnerIn', 'ZweiteImpfungkumulativ',
       'ZweiteImpfungDifferenzzumVortag', 'Auffrischimpfungen'],
      dtype='object')

In [71]:
translation = {
      timestamp: 'timestamp',
      ISODate: 'calendar_days',
      IdBundesland: 'bundesland_id',
      Bundesland: 'subdivision_1',
      Impfungenkumulativ: 'first_vaccination',
      DifferenzzumVortag: 'first_vaccination_delta',
      IndikationnachAlter: 'indication_by_age',
      BeruflicheIndikation: 'indication_by_profession',
      MedizinischeIndikation: 'indication_by_medical',
      PflegeheimbewohnerIn: 'nursing_home_resident',
      ZweiteImpfungkumulativ: 'second_vaccination',
      ZweiteImpfungDifferenzzumVortag: 'second_vaccination_delta',
      Auffrischimpfungen: 'booster_vaccination'
}

In [75]:
test2.rename(columns=translation, inplace=True)
test2.head()

,timestamp,ISODate,IdBundesland,subdivision_1,first_vaccination,first_vaccination_delta,indication_by_age,indication_by_profession,indication_by_medical,nursing_home_resident,second_vaccination,second_vaccination_delta,booster_vaccination
0,1609113600,2020-12-28,0,Gesamt,21566,1357,5833,7618,962,11646,0,0,0
1,1609113600,2020-12-28,1,Schleswig-Holstein,809,0,213,239,344,553,0,0,0
2,1609113600,2020-12-28,2,Hamburg,445,0,197,222,0,223,0,0,0
3,1609113600,2020-12-28,3,Niedersachsen,334,0,42,116,140,306,0,0,0
4,1609113600,2020-12-28,4,Bremen,420,0,205,87,0,0,0,0,0